# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeRi-iFGFA3w6DQdRqtZsb4zzKTxFkfn
"""

import numpy as np
import pandas as pd

#membaca dataset
buah=pd.read_table('fruit_data_with_colors.txt')
buah.head(100)

buah.info()

label_mapping=dict(zip(buah.fruit_label.unique(), buah.fruit_name.unique()))
label_mapping

buah['fruit_name'].value_counts()

import seaborn as sns
g=sns.PairGrid(buah,hue="fruit_name")
g.map_diag(sns.histplot)
g.map_offdiag(sns.scatterplot)

buah=buah.drop(["fruit_name", "fruit_subtype"],axis=1 )
buah.head(100)

x=buah[["mass", "width", "height", "color_score"]]
y=buah['fruit_label']

from sklearn import preprocessing
scaler=preprocessing.MinMaxScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, random_state=0)
x_train_scaled, x_test_scaled, y_train_scaled, y_test_scaled=train_test_split(x_scaled, y, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
m1=KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train)
acc1=m1.score(x_test_scaled, y_test)
print(acc1)

#k terbaik
K=np.arange(2,30)
akurasi=[]
for k in K:
  m2=KNeighborsClassifier(n_neighbors=k).fit(x_train_scaled, y_train)
  acc1=m2.score(x_test_scaled, y_test)
  akurasi.append(acc1)
  print(akurasi)

import matplotlib.pyplot as plt
plt.plot(K, akurasi)
plt.show()